language: node_js
node_js:
  - "4"
services:
  - mongodb
before_install:
  - npm install -g gulp bower
before_script:
  - gulp
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - ./deploy.sh
env:
  global:
    - secure: "kYFuuixC+ZqvW8kQ4Z4DBpmwanhZcYKw6hRgfv5rpNvhoJ+4fVXPJC3BJX1JHtpHEca5mSrXnGKtOt5/Zl3MIEjvZJGvLfMhi39i1LEnxt3QbmsVOS5Zqvz1edP1uT5gNwtiZt12BfNNknlAmTZj56H7lGJ+dvG4uaxnQs7/HgTPiIqLZTTmRY+qYRJ+eOLT0sNzUH8DtfYHlsvMFdMaQyBIQXE9v52WMdeqzwqMnY63d0OCV+EHwBIzQP5QCDlbqc8/kTZFeY9uF3dlW/xKPWIE4d5Yzv16ii6U5M+rXgum7ZZ1Jqfb9oxzFr54iNochSPT1Do3z2U9dff0tXJxnWVxdWvw4Yc4bstixu3ba+O39g278D6LdY80zAUUKKBihzoD05abZL1sBYtP3NvV1SSUSrES2uSxe7/OGK3mWiG6C72LhBkf8ZCd49mqVyUrikBxV4wIx9koS5dUC/Epqdlk+xXuewhQ9yh7Hv410KNwwEKtGfpEmwWVRC3qupwmk6ygqplYv07NtGXbdyppVEBCAju+LINzfQKXQ5bXfHDeIrLJCs2yrtYAHIrIyDGTRFVMiUoWstNIoppMyTJqfdqRSP/tiLM/BrJfndRItJhP1cTxWw5rn0BJJIobk7MjX/wzpYBZE2lWLr9gsCPfyYMpPvw7oebWl2DPgyOYRKc="
    - secure: "aKr31lON2roprb+5IiBpwXnPwhIwt9lUdC+uh5BLF7+D+LNaEAQPYliozYL2m7a9AedihCw14O1fyjUrZE1pfUui5NkWHwUV1MJNQ6eJ+oJQcMt1AbHc09meil9tGJKSZCWCBxCl4pUnaJaWuVHur8UjNuKbHCFYoOtEzT0VRHW8VXoL/cizYdr4XoXPQNXXvWed/qQ46fglcu0756Stmgu3YkdSUl5uzRQdrr1I9P2FcHbOgJQsnEa8Z0QLO0GW07csrbnXtLP/WpC4GNDh4qSFiKh9Gby4HPF4cqxM5aiqekRfQWXfyP1+knLhaZAQ6ghgzUIQDo29bIZG2x0e/lL7LBcz/ePt344ztOwzPcvxpbIeS8wuZE1ID+ljspAbmU27mYHyS62EJ/EAHIJbkgTMSs840ZQowAzvB1bc8EyEomgW3eY3SzsjItzqDt7cbzA6u+VmrpDXk0fcc9bMQuS7ZRJcOtLbAEyJ4lBTKhgMvEovpV9mNNFH4zUObODgVwM9k3H5mZ3IenO3aqPHNcs1RcgB2ryaoeps/Q8qDMMEsU38f7gwV7/5a07iiXM7dn/0I85sgbZAmKW3cwXQ/PzQDLjI0ygY5cqPfIgRIOnLml/jk1SPySG/TgV4U+7Eko6ZUOMxn3QS5w3kLlEizvfYWejlp98XlPKFIuCs14U="
    - secure: "QvoR1B3BBJfgafU3XvGc3/ejYI8zXtgYU2Mq2TVNNGWQk01UV6Abo2Hs9UghTL9dVdfk1pd1gQtxMefSaVMTMUGzsP+rg8TOWH0HEG6cmfNi8dOL0ujuNvjvP6Sf25AWp1Gisp6b1Y5Q2C3i2Ljx8z7Mz7CGb9JZbuSLv98MA7Dpl/eYj5ZM+2L9FEMQtZUt65IVvGvXCzIGBeMWuozhRZI61KPuEXGMvM5GEnVcD/pImA/irMal7C4olGuGo9jw1sxlikh0XoQYBlAuPA00v1oy/x78eOCT2T1U8lnuuU4UvE/qv/0fz6lQ/iDmTISl/UJdnRJSfjg6Ctl3xd7M4BdYpI5AatL6t6oZ74gnN8JJWSFspbCnsNu8fXpQ4WLxG2ORoMfpAJZH/+SzWkudstkuJJ+t9EkqDGngkslPaLsNjWNNuXjXHcLuldvoEaAKHz8pDKYyD1gPetq2v6GWS8Ls0lFIfB5+ZxU9Qx8UMMAseHmbJH0a8alODxiCH8aTdakfzPbcsOckMM8GJYN/Ep9qasDajvQFPKXJYfD9Lt4/il8zrnMwIvBkAtVEne0qLVz/5Gq91ZhvkfUUW8hmeu7mb2zdC1c3H+ZfkbdyVWghVjQMGAnZlmUtdnYEk+eKG76odYEdViUvpNaNN22PLyx8/0PPRx2YCkaWdiirQjQ="
